# Generated by Django 3.2.5 on 2021-07-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_completed_todo_complated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_date',)},
        ),
    ]
